import { ParticleEmitter, DefaultPlayerEntity, World } from "hytopia";

/**
 * Types de particules disponibles
 */
export type ParticleType =
  | "particle1"
  | "particle2"
  | "particle3"
  | "particle4"
  | "particle5"
  | "particle6"
  | "particle7"
  | "particle8"
  | "particle9"
  | "particle10"
  | "particle11"
  | "particle12"
  | "particle13"
  | "particle14"
  | "particle15"
  | "particle16"
  | "particle17"
  | "particle18"
  | "particle19"
  | "particle20"
  | "particle21"
  | "particle22"
  | "particle23"
  | "particle24"
  | "particle25"
  | "particle26"
  | "particle27"
  | "particle28"
  | "particle29"
  | "particle30"
  | "particle31"
  | "particle32"
  | "particle33"
  | "particle34"
  | "particle35"
  | "particle36"
  | "particle37"
  | "particle38"
  | "particle39"
  | "particle40"
  | "particle41"
  | "particle42"
  | "particle43"
  | "particle44"
  | "particle45"
  | "particle46"
  | "particle47"
  | "particle48"
  | "particle49"
  | "particle50";

/**
 * Configuration d'un émetteur de particules
 */
interface ParticleConfig {
  textureUri: string;
  colorStart: { r: number; g: number; b: number };
  sizeStart: number;
  sizeStartVariance: number;
  sizeEnd: number;
  sizeEndVariance: number;
  lifetime: number;
  lifetimeVariance: number;
  rate: number;
  maxParticles: number;
  velocity: { x: number; y: number; z: number };
  velocityVariance: { x: number; y: number; z: number };
  opacityStart: number;
  opacityEnd: number;
  offset: { x: number; y: number; z: number };
}

/**
 * Configurations prédéfinies pour chaque type de particule
 */
const PARTICLE_CONFIGS: Record<ParticleType, ParticleConfig> = {
  particle1: {
    // Particule de feu (configuration actuelle)
    textureUri: "particles/fire.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 30,
    velocity: { x: 0, y: 0.5, z: 0 },
    velocityVariance: { x: 0.3, y: 0.2, z: 0.3 },
    opacityStart: 0.8,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle2: {
    // Particule magique
    textureUri: "particles/magic.png",
    colorStart: { r: 200, g: 100, b: 255 },
    sizeStart: 0.1,
    sizeStartVariance: 0.02,
    sizeEnd: 0.5,
    sizeEndVariance: 0.03,
    lifetime: 2.5,
    lifetimeVariance: 0.6,
    rate: 10,
    maxParticles: 25,
    velocity: { x: 0, y: 0.4, z: 0 },
    velocityVariance: { x: 0.4, y: 0.3, z: 0.4 },
    opacityStart: 0.9,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle3: {
    // Particule de fumée
    textureUri: "particles/smoke.png",
    colorStart: { r: 150, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.04,
    sizeEnd: 0.5,
    sizeEndVariance: 0.05,
    lifetime: 3,
    lifetimeVariance: 0.8,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle4: {
    textureUri: "particles/fire_01.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 30,
    velocity: { x: 0, y: 0.5, z: 0 },
    velocityVariance: { x: 0.3, y: 0.2, z: 0.3 },
    opacityStart: 0.8,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle5: {
    textureUri: "particles/magic_01.png",
    colorStart: { r: 200, g: 100, b: 255 },
    sizeStart: 0.1,
    sizeStartVariance: 0.02,
    sizeEnd: 0.5,
    sizeEndVariance: 0.03,
    lifetime: 2.5,
    lifetimeVariance: 0.6,
    rate: 10,
    maxParticles: 25,
    velocity: { x: 0, y: 0.4, z: 0 },
    velocityVariance: { x: 0.4, y: 0.3, z: 0.4 },
    opacityStart: 0.9,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle6: {
    textureUri: "particles/magic_02.png",
    colorStart: { r: 200, g: 100, b: 255 },
    sizeStart: 0.1,
    sizeStartVariance: 0.02,
    sizeEnd: 0.5,
    sizeEndVariance: 0.03,
    lifetime: 2.5,
    lifetimeVariance: 0.6,
    rate: 10,
    maxParticles: 25,
    velocity: { x: 0, y: 0.4, z: 0 },
    velocityVariance: { x: 0.4, y: 0.3, z: 0.4 },
    opacityStart: 0.9,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle7: {
    textureUri: "particles/magic_03.png",
    colorStart: { r: 200, g: 100, b: 255 },
    sizeStart: 0.1,
    sizeStartVariance: 0.02,
    sizeEnd: 0.5,
    sizeEndVariance: 0.03,
    lifetime: 2.5,
    lifetimeVariance: 0.6,
    rate: 10,
    maxParticles: 25,
    velocity: { x: 0, y: 0.4, z: 0 },
    velocityVariance: { x: 0.4, y: 0.3, z: 0.4 },
    opacityStart: 0.9,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle8: {
    textureUri: "particles/magic_04.png",
    colorStart: { r: 200, g: 100, b: 255 },
    sizeStart: 0.1,
    sizeStartVariance: 0.02,
    sizeEnd: 0.5,
    sizeEndVariance: 0.03,
    lifetime: 2.5,
    lifetimeVariance: 0.6,
    rate: 10,
    maxParticles: 25,
    velocity: { x: 0, y: 0.4, z: 0 },
    velocityVariance: { x: 0.4, y: 0.3, z: 0.4 },
    opacityStart: 0.9,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle9: {
    textureUri: "particles/magic_05.png",
    colorStart: { r: 150, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.04,
    sizeEnd: 0.5,
    sizeEndVariance: 0.05,
    lifetime: 3,
    lifetimeVariance: 0.8,
    rate: 10,
    maxParticles: 25,
    velocity: { x: 0, y: 0.4, z: 0 },
    velocityVariance: { x: 0.4, y: 0.3, z: 0.4 },
    opacityStart: 0.9,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle10: {
    textureUri: "particles/smoke_01.png",
    colorStart: { r: 150, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.04,
    sizeEnd: 0.5,
    sizeEndVariance: 0.05,
    lifetime: 3,
    lifetimeVariance: 0.8,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle11: {
    textureUri: "particles/smoke_02.png",
    colorStart: { r: 150, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.04,
    sizeEnd: 0.5,
    sizeEndVariance: 0.05,
    lifetime: 3,
    lifetimeVariance: 0.8,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle12: {
    textureUri: "particles/smoke_03.png",
    colorStart: { r: 150, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.04,
    sizeEnd: 0.5,
    sizeEndVariance: 0.05,
    lifetime: 3,
    lifetimeVariance: 0.8,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle13: {
    textureUri: "particles/smoke_04.png",
    colorStart: { r: 150, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.04,
    sizeEnd: 0.5,
    sizeEndVariance: 0.05,
    lifetime: 3,
    lifetimeVariance: 0.8,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle14: {
    textureUri: "particles/smoke_05.png",
    colorStart: { r: 150, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.04,
    sizeEnd: 0.5,
    sizeEndVariance: 0.05,
    lifetime: 3,
    lifetimeVariance: 0.8,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle15: {
    textureUri: "particles/circle_01.png",
    colorStart: { r: 255, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle16: {
    textureUri: "particles/circle_02.png",
    colorStart: { r: 255, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle17: {
    textureUri: "particles/circle_03.png",
    colorStart: { r: 255, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle18: {
    textureUri: "particles/circle_04.png",
    colorStart: { r: 255, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle19: {
    textureUri: "particles/circle_05.png",
    colorStart: { r: 255, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle20: {
    textureUri: "particles/dirt_01.png",
    colorStart: { r: 255, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle21: {
    textureUri: "particles/dirt_02.png",
    colorStart: { r: 255, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle22: {
    textureUri: "particles/dirt_03.png",
    colorStart: { r: 255, g: 150, b: 150 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle23: {
    textureUri: "particles/flame_01.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle24: {
    textureUri: "particles/flame_02.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle25: {
    textureUri: "particles/flame_03.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle26: {
    textureUri: "particles/flame_04.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle27: {
    textureUri: "particles/flame_05.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle28: {
    textureUri: "particles/flame_06.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle29: {
    textureUri: "particles/light_01.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle30: {
    textureUri: "particles/light_02.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle31: {
    textureUri: "particles/light_03.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  //Light 4
  particle32: {
    textureUri: "particles/flare_01.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle33: {
    textureUri: "particles/muzzle_01.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle34: {
    textureUri: "particles/muzzle_02.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle35: {
    textureUri: "particles/muzzle_03.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle36: {
    textureUri: "particles/muzzle_04.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle37: {
    textureUri: "particles/muzzle_05.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle38: {
    textureUri: "particles/scorch_01.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle39: {
    textureUri: "particles/scorch_02.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle40: {
    textureUri: "particles/scorch_03.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle41: {
    textureUri: "particles/spark_01.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle42: {
    textureUri: "particles/spark_02.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle43: {
    textureUri: "particles/spark_03.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle44: {
    textureUri: "particles/spark_04.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle45: {
    textureUri: "particles/spark_05.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle46: {
    textureUri: "particles/star_01.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle47: {
    textureUri: "particles/star_02.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle48: {
    textureUri: "particles/star_03.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle49: {
    textureUri: "particles/star_04.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
  particle50: {
    textureUri: "particles/star_05.png",
    colorStart: { r: 255, g: 150, b: 0 },
    sizeStart: 0.1,
    sizeStartVariance: 0.03,
    sizeEnd: 0.5,
    sizeEndVariance: 0.02,
    lifetime: 2,
    lifetimeVariance: 0.5,
    rate: 10,
    maxParticles: 20,
    velocity: { x: 0, y: 0.3, z: 0 },
    velocityVariance: { x: 0.5, y: 0.2, z: 0.5 },
    opacityStart: 0.6,
    opacityEnd: 0,
    offset: { x: 0, y: -0.5, z: 0 },
  },
};

/**
 * Gestionnaire de particules pour les joueurs
 * Permet de créer et gérer les émetteurs de particules attachés aux joueurs
 */
export class ParticleManager {
  /**
   * Crée un émetteur de particules pour un joueur selon le type sélectionné
   * @param particleType Type de particule à créer
   * @param playerEntity Entité du joueur à laquelle attacher les particules
   * @param world Monde dans lequel spawner les particules
   * @returns L'émetteur de particules créé
   */
  static createParticleEmitter(
    particleType: ParticleType,
    playerEntity: DefaultPlayerEntity,
    world: World
  ): ParticleEmitter {
    const config = PARTICLE_CONFIGS[particleType];

    const emitter = new ParticleEmitter({
      attachedToEntity: playerEntity,
      offset: config.offset,
      textureUri: config.textureUri,
      colorStart: config.colorStart,
      sizeStart: config.sizeStart,
      sizeStartVariance: config.sizeStartVariance,
      sizeEnd: config.sizeEnd,
      sizeEndVariance: config.sizeEndVariance,
      lifetime: config.lifetime,
      lifetimeVariance: config.lifetimeVariance,
      rate: config.rate,
      maxParticles: config.maxParticles,
      velocity: config.velocity,
      velocityVariance: config.velocityVariance,
      opacityStart: config.opacityStart,
      opacityEnd: config.opacityEnd,
    });

    emitter.spawn(world);
    return emitter;
  }

  /**
   * Vérifie si un type de particule est valide
   * @param particleType Type à vérifier
   * @returns true si le type est valide
   */
  static isValidParticleType(
    particleType: string
  ): particleType is ParticleType {
    return particleType in PARTICLE_CONFIGS;
  }

  /**
   * Retourne le type de particule par défaut
   * @returns Le type de particule par défaut
   */
  static getDefaultParticleType(): ParticleType {
    return "particle1";
  }
}
